project:
  type: website
  output-dir: docs

website:
  title: "Missy Zhang"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - contact.qmd
      - href: Missy Zhang_resume(DS).pdf
        text: Resume

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    
    



