project:
  type: website

website:
  title: "Missy Zhang"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    



