---
title: "Welcome to my site"
---

Hi, I'm Missy Zhang, a Bachelor of Information student at the University of Toronto. As a emerging data scientist, I am passionate about leveraging data to drive insights and make informed decisions. Throughout my academic journey, I have honed my skills in data analysis, statistics, and programming languages such as Python and R.

In addition to my coursework, I have participated in various data-related projects, including analyzing factor combination that affects innovation performance in old industrial bases in China, analyzing crime rate data in Toronto neighborhoods, and designing data visualizations to communicate complex information. I am also actively involved in the university's data science community, attending data science hackathons and networking events to expand my knowledge and connect with like-minded individuals.

As I move towards the next chapter of my career, I am eager to apply my skills and knowledge in a data science role. I am excited about the opportunities to work with big data, build predictive models, and derive insights that can help businesses make better decisions. Thank you for considering my portfolio, and I look forward to discussing potential opportunities with you.
